# Generated by Django 2.1 on 2019-04-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
